---
ocean:
  version: "1"
steps:
- engines:
  - name: file-browser
    variables:
    - name: file_browser_port
      value: reserve_port()
    orchestrator:
      type: Orchestrator::MainWithWorkers
      deploy_to_main: true
      deploy_to_workers: false
      container_user: "{{ workspace.user.uid }}:{{ workspace.user.gid }}"
      container_workdir: "/work"
      engine_mount: "/etc/ocean"
      data_stores_mount: "{{ orchestrator.container.workdir }}"
      ssh_mount: "/home/{{ workspace.user.name }}/.ssh"
      main_env_vars:
        - name: FB_PORT
          value: "{{ vars.file_browser_port }}"
        - name: FB_NOAUTH
          value: true
        - name: FB_DATABASE
          value: "{{ orchestrator.container.mounts.engine }}/etc/file_manager.db"
        - name: FB_ROOT
          value: "{{ orchestrator.container.workdir }}"
      main_entrypoint: ''
      worker_entrypoint: ''
      main_command: ''
      worker_command: ''
      snapshot_definition:
        registry_name: docker_hub
        image_name: filebrowser/filebrowser
        snapshot_name: latest
    views:
      buttons:
        - node_target: main
          label: Open File Manager
          url: http://{{ views.buttons.self.node.public_ip }}:{{ vars.file_browser_port }}
