---
ocean:
  version: "1"
images:
  - name: filebrowser
    registry: docker_hub
    image: filebrowser/filebrowser
    tag: latest
steps:
- engines:
  - name: browser
    settings:
      - name: password
        label: Password
        type: input
        default_value: password
    networking:
      dns:
        enabled: true
        default_value: files
        label: File Manager URL
      ports:
        - name: browser
          public: true
    deployment:
      strategy: main
    container:
      image:
        name: filebrowser
        editable: false
      user: "{{ workspace.user.uid }}:{{ workspace.user.gid }}"
      workdir: "/work"
      mounts:
        app_files:
          - name: browser
            app_files_path: browser
            container_path: /ocean/etc/browser
            readonly: false
        data_stores: "{{ engines.browser.container.workdir }}"
      env_vars:
        - name: FB_PORT
          value: "{{ engines.browser.networking.ports.browser.value }}"
        - name: FB_NOAUTH
          value: "true"
        - name: FB_DATABASE
          value: "{{ engines.browser.container.mounts.app_files.browser.container_path }}/filebrowser.db"
        - name: FB_ROOT
          value: "{{ engines.browser.container.workdir }}"
    ui:
      buttons:
        - label: Open File Manager
          url: "http://{{ engines.browser.networking.dns.url }}:{{ engines.browser.networking.ports.browser.value }}"
