---
ocean:
  version: "1"
images:
  - name: filebrowser
    registry: docker_hub
    image: filebrowser/filebrowser
    tag: latest
    snapshottable: false
steps:
- engines:
  - name: browser
    networking:
      dns:
        enabled: true
        default_value: files
        label: File Manager URL
      ports:
        - name: browser
          public: true
    deployment:
      strategy: main
    container:
      image_name: filebrowser
      user: "{{ workspace.user.uid }}:{{ workspace.user.gid }}"
      workdir: "/work"
      mounts:
        app_files:
          - name: filebrowser
            app_files_path: filebrowser
            container_path: /ocean/etc/filebrowser
            readonly: false
        data_stores: "{{ engines.browser.container.workdir }}"
      env_vars:
        - name: FB_PORT
          value: "{{ engines.browser.ports.filebrowser.value }}"
        - name: FB_NOAUTH
          value: true
        - name: FB_DATABASE
          value: "{{ engines.browser.container.mounts.app_files.filebrowser.container_path }}/filebrowser.db"
        - name: FB_ROOT
          value: "{{ engines.browser.container.workdir }}"
  ui:
    buttons:
      - label: Open File Manager
        url: "http://{{ engines.browser.networking.dns.url }}:{{ engines.browser.ports.filebrowser.value }}"
