---
ocean:
  version: "1"
steps:
- engines:
  - name: file-browser
    vars:
      - name: file_browser_port
        value: reserve_port()
    orchestrator:
      type: Orchestrator::MainWithWorkers
      deploy_to_main: true
      deploy_to_workers: false
      snapshot:
        registry:
          name: docker_hub
        image:
          name: filebrowser/filebrowser
        name: latest
      container:
        user: "{{ workspace.user.uid }}:{{ workspace.user.gid }}"
        workdir: "/work"
        mounts:
          engine: "/etc/ocean"
          data_stores: "{{ engines.file-browser.orchestrator.container.workdir }}"
          ssh: "/home/{{ workspace.user.name }}/.ssh"
      nodes:
        main:
          env_vars:
            - name: FB_PORT
              value: "{{ engines.file-browser.vars.file_browser_port }}"
            - name: FB_NOAUTH
              value: true
            - name: FB_DATABASE
              value: "{{ engines.file-browser.orchestrator.container.mounts.engine }}/etc/file_manager.db"
            - name: FB_ROOT
              value: "{{ engines.file-browser.orchestrator.container.workdir }}"
    views:
      buttons:
        - node_target: main
          label: Open File Manager
          url: "http://{{ engines.file-browser.views.buttons.self.node.public_ip }}:{{ engines.file-browser.vars.file_browser_port }}"
