---
ocean:
  version: "1"
snapshots:
  - name: filebrowser
    registry: docker_hub
    image: filebrowser/filebrowser
    tag: latest
steps:
- engines:
  - name: browser
    vars:
      - name: port
        value: "{% reserve_public_port %}"
    orchestrator:
      snapshot_name: filebrowser
      deployment_strategy: main
      container:
        user: "{{ workspace.user.uid }}:{{ workspace.user.gid }}"
        workdir: "/work"
        mounts:
          files:
            - name: filebrowser
              app_path: filebrowser
              container_path: /ocean/etc/filebrowser
              readonly: false
          data_stores: "{{ engines.browser.orchestrator.container.workdir }}"
          ssh: "/home/{{ workspace.user.name }}/.ssh"
        nodes:
          main:
            env_vars:
              - name: FB_PORT
                value: "{{ engines.browser.vars.port }}"
              - name: FB_NOAUTH
                value: true
              - name: FB_DATABASE
                value: "{{ engines.browser.orchestrator.container.mounts.files.filebrowser.container_path }}/etc/filebrowser.db"
              - name: FB_ROOT
                value: "{{ engines.browser.orchestrator.container.workdir }}"
    ui:
      buttons:
        - node_target: main
          label: Open File Manager
          url: "http://{{ engines.browser.ui.buttons.self.node.public_ip }}:{{ engines.browser.vars.port }}"
